# Generated by Django 4.2.6 on 2023-11-04 19:52

import app1.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idTipoprod', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreTipo', models.CharField(max_length=100, verbose_name='Nombre tipo producto')),
                ('descripcionTipo', models.CharField(max_length=100, verbose_name='Descripción de la categoría')),
                ('fotoTipo', models.ImageField(blank=True, default='categorias/categoria.png', null=True, upload_to=app1.models.TipoProducto.generar_nombre)),
            ],
            options={
                'verbose_name': 'TipoProducto',
                'verbose_name_plural': 'TipoProductos',
                'db_table': 'tipoProducto',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del usuario')),
                ('paterno', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('materno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido materno')),
                ('numeroContacto', models.PositiveIntegerField(default=912345678, verbose_name='Numero de contacto')),
                ('email', models.CharField(max_length=100, verbose_name='Correo del usuario')),
                ('contraseña', models.CharField(max_length=100, verbose_name='Contraseña del usuario')),
                ('fechaNaci', models.DateField(verbose_name='Fecha de nacimiento')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['rut', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('marcaProduc', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('precio', models.PositiveIntegerField(default=100000, verbose_name='Precio del productos')),
                ('imagenProduc', models.ImageField(default='productos/producto.png', null=True, upload_to=app1.models.Producto.generar_nombre)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.tipoproducto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('idOrden', models.BigAutoField(primary_key=True, serialize=False)),
                ('metodoPago', models.CharField(choices=[('D', 'Debito'), ('C', 'Credito'), ('P', 'Pre-compra')], default='D', max_length=1)),
                ('total', models.PositiveIntegerField(default=100000, verbose_name='Total de la compra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.usuario')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'db_table': 'orden',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('idDetalleOrd', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=10, verbose_name='kilos del producto')),
                ('precio', models.PositiveIntegerField(default=10, verbose_name='precio producto')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.orden')),
            ],
            options={
                'verbose_name': 'DetalleOrden',
                'verbose_name_plural': 'DetallesOrdenes',
                'db_table': 'detalleOrden',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idProducto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='nombre', max_length=50, verbose_name='Nombre de producto')),
                ('cantidad', models.PositiveIntegerField(default=10, verbose_name='Cantidad de productos')),
                ('marcaProduc', models.CharField(max_length=50, verbose_name='Marca del producto')),
                ('precio', models.PositiveIntegerField(default=0, verbose_name='Precio del productos')),
                ('imagen', models.ImageField(default='carro/carrito.png', null=True, upload_to=app1.models.Carrito.generar_nombre)),
                ('tipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.tipoproducto')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'db_table': 'carrito',
            },
        ),
    ]
