# Generated by Django 4.2.5 on 2023-11-19 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_compra', models.IntegerField(verbose_name='Numero de la compra')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('total_compra', models.IntegerField(verbose_name='Total de la compra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usuario', verbose_name='Cliente que realizo la compra')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compra',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad_comprada', models.CharField(max_length=10)),
                ('total', models.IntegerField()),
                ('imagen', models.CharField(max_length=160)),
                ('estado', models.CharField(default='En espera', max_length=30)),
            ],
            options={
                'verbose_name': 'DetalleCompra',
                'verbose_name_plural': 'DetallesCompras',
                'db_table': 'detalleCompra',
            },
        ),
        migrations.CreateModel(
            name='PreCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_precompra', models.IntegerField(verbose_name='Numero de la precompra')),
                ('fecha_precompra', models.DateTimeField(auto_now_add=True)),
                ('total_precompra', models.IntegerField(verbose_name='Total de la precompra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usuario', verbose_name='Cliente que realizo la precompra')),
            ],
            options={
                'verbose_name': 'PreCompra',
                'verbose_name_plural': 'PreCompras',
                'db_table': 'precompra',
            },
        ),
        migrations.RemoveField(
            model_name='orden',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='DetalleOrden',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='precompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.precompra', verbose_name='PreCompra'),
        ),
    ]
