# Generated by Django 4.2.5 on 2023-11-19 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_compra_detallecompra_precompra_remove_orden_usuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
    ]
