# Generated by Django 4.2.5 on 2023-11-19 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_delete_detallecompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePreCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad_comprada', models.CharField(max_length=10)),
                ('total', models.IntegerField()),
                ('imagen', models.CharField(max_length=160)),
                ('estado', models.CharField(default='En espera', max_length=30)),
                ('precompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.precompra', verbose_name='PreCompra')),
            ],
            options={
                'verbose_name': 'DetallePreCompra',
                'verbose_name_plural': 'DetallesPreCompras',
                'db_table': 'detallePreCompra',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad_comprada', models.CharField(max_length=10)),
                ('total', models.IntegerField()),
                ('imagen', models.CharField(max_length=150)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.compra', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'DetalleCompra',
                'verbose_name_plural': 'DetallesCompras',
                'db_table': 'detalleCompra',
            },
        ),
    ]
