# Generated by Django 4.2.5 on 2023-11-20 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_total_detallecompra_precio_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='nro_compra',
        ),
        migrations.RemoveField(
            model_name='precompra',
            name='nro_precompra',
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 21, 19, 16, 576610, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='precompra',
            name='fecha_precompra',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 21, 19, 16, 576610, tzinfo=datetime.timezone.utc)),
        ),
    ]
