# Generated by Django 4.2.5 on 2023-11-20 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_compra_nro_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='precompra',
            name='fecha_precompra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
