# Generated by Django 4.2.5 on 2023-11-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_compra_fecha_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='imagen',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
