# Generated by Django 4.2.5 on 2023-11-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_producto_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario (distinto al nombre anterior)'),
        ),
    ]
