# Generated by Django 4.2.5 on 2023-11-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_carrito_usuario_alter_producto_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleprecompra',
            name='estado',
        ),
    ]
