# Generated by Django 4.2.5 on 2023-11-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_detalleprecompra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='precompra',
            name='estado',
            field=models.CharField(default='En espera', max_length=30),
        ),
    ]
