# Generated by Django 4.2.5 on 2023-11-28 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_precompra_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('paterno', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('materno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido materno')),
                ('numeroContacto', models.PositiveIntegerField(default=912345678, verbose_name='Numero de contacto')),
                ('email', models.CharField(max_length=100, verbose_name='Correo del usuario')),
                ('nombre_usuario', models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario (distinto al nombre anterior)')),
                ('contraseña', models.CharField(max_length=100, verbose_name='Contraseña del usuario')),
                ('fechaNaci', models.DateField(verbose_name='Fecha de nacimiento')),
                ('fecha_contratacion', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de contratacion')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cajero',
                'verbose_name_plural': 'Cajeros',
                'db_table': 'cajero',
            },
        ),
    ]
