# Generated by Django 4.2.5 on 2023-11-28 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_cajero_fecha_contratacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajero',
            name='nombre_usuario',
        ),
    ]
